### ISSUE TITLE
[DB] Luna - missing tile title and thumbnail

### ISSUE THREAD

**Issue by cheater** [tauqua/gog-galaxy-itch.io#6] opened 2020-06-14 17:12 UTC
On the library view, the game Luna is missing the game title and the tile thumbnail is just black. Apparently there are two games called Luna on IGDB, and this is what might be confusing your plugin. The game I'm talking about is Luna by the studio Funomena. The other game is Luna by Lushboy Studios. In addition, Luna by Funomena has two separate entries.

Game title: Luna

Itch.io link: https://funomena.itch.io/luna

IGDB page:
Luna by Funomena (correct game, no thumbnail in IGDB, no title or thumbnail in Galaxy): https://www.igdb.com/games/luna--2
Luna by Funomena (also the correct game, has correct thumbnail on IGDB): https://www.igdb.com/games/luna--1

Luna by Lushboy Studios (wrong game, IGDB has the thumbnail for Luna by Funomena ! which should be removed): https://www.igdb.com/games/luna

Steam or other store link:
Luna by Funomena (correct game): https://store.steampowered.com/app/605770/Luna/
Luna by Lushboy Studios (wrong game): https://store.steampowered.com/app/666810/Luna/

Itch.io ID:
Luna by Funomena (correct game, the one I have, that was found in the log file): 271280

GOG Database lookup link: https://gamesdb.gog.com/platforms/itch/external_releases/271280

**Comment by Fielran** [comment] 2020-06-27 07:00
I had what appeared to be the same issue; however, on closer examination information from both games had been mashed into all three igdb entries. I spent about an hour sorting out the correct information into each on igdb, and the issue is now fixed for me in GOG galaxy as well.

Lushboy Studios: https://www.igdb.com/games/luna
Funomena: https://www.igdb.com/games/luna--2

**Comment by code2bayaa** [comment] 2020-07-28 13:54
Hello I can't seem to find the image url for the games....please assist

**Closed** 2022-03-09 19:15 UTC
Labels: database
